CREATE TABLE Words (
    w_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    w_word VARCHAR(32) NOT NULL,
    PRIMARY KEY (w_id)
)
ENGINE=INNODB;



CREATE TABLE Materiaux (
    n_m_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    n_m_date DATE NOT NULL,
    n_m_nommodif VARCHAR(24) NOT NULL,
    n_m_nom VARCHAR(62) NOT NULL,
    n_m_famille CHAR(9) NOT NULL,
    n_m_provenance VARCHAR(24),
    n_m_distance SMALLINT,
    n_m_fournisseur VARCHAR(32),
    n_m_traitement VARCHAR(62),
    n_m_fabrication TEXT,
    n_m_qualitedefaut TEXT,
    n_m_application TEXT,
    n_m_prix FLOAT UNSIGNED,
    n_m_composition VARCHAR(32),
    n_m_massevolumique FLOAT(7,2) UNSIGNED,
    n_m_young MEDIUMINT UNSIGNED,
    n_m_poisson FLOAT(3,3) UNSIGNED,
    n_m_limiteelast SMALLINT UNSIGNED,
    n_m_resistance_traction SMALLINT UNSIGNED,
    n_m_resistance_compression SMALLINT UNSIGNED,
    n_m_vickers SMALLINT UNSIGNED,
    n_m_tenacite FLOAT(7,3) UNSIGNED,
    n_m_temp_fusion SMALLINT,
    n_m_temp_mini SMALLINT,
    n_m_temp_maxi SMALLINT,
    n_m_chaleurspecifique SMALLINT UNSIGNED,
    n_m_coefficientdilatation SMALLINT,
    n_m_conductivite_thermique SMALLINT UNSIGNED,
    n_m_resistivite_elec FLOAT UNSIGNED,
    n_m_optique VARCHAR(12),
    n_m_durabilite_aqueux TINYINT,
    n_m_durabilite_acide TINYINT,
    n_m_durabilite_base TINYINT,
    n_m_durabilite_huile TINYINT,
    n_m_durabilite_alcool TINYINT,
    n_m_durabilite_gaz TINYINT,
    n_m_durabilite_construit TINYINT,
    n_m_durabilite_froid TINYINT,
    n_m_durabilite_temp_moyenne TINYINT,
    n_m_durabilite_chaud TINYINT,
    n_m_inflammabilite TINYINT,
    n_m_energiegrise INT,
    n_m_co2_p FLOAT,
    n_m_eau_p INT,
    n_m_recyclable CHAR(3),
    n_m_reutilisable CHAR(3),
    n_m_biodegradable CHAR(3),
    n_m_incinerable CHAR(3),
    n_m_renouvelable CHAR(3),
    n_m_toxicite TEXT DEFAULT 'pas d\'info',
    n_m_productionannuelle INT,
    n_m_reserves INT,
    n_m_commentaire TEXT,
    PRIMARY KEY (n_m_id)
)
ENGINE=INNODB;



CREATE TABLE Pieces (
    p_id SMALLINT UNSIGNED AUTO_INCREMENT,
    p_date DATE NOT NULL,
    p_nommodif VARCHAR(24) NOT NULL,
    p_nom VARCHAR(48),
    p_materiau_principal VARCHAR(62),
    p_materiau_secondaire VARCHAR(62),
    p_forme VARCHAR(48),
    p_longueur FLOAT UNSIGNED,
    p_largeur FLOAT UNSIGNED,
    p_hauteur FLOAT UNSIGNED,
    p_quantite FLOAT UNSIGNED,
    p_utilisation TEXT,
    p_outil TEXT,
    p_etat TINYINT UNSIGNED,
    p_utilisation_init VARCHAR(48),
    p_thermique VARCHAR(12),
    p_acoustique VARCHAR(12),
    p_electrique VARCHAR(12),
    p_resistance VARCHAR(12),
    p_flexibilite VARCHAR(12),
    p_elasticite VARCHAR(12),
    p_optique VARCHAR(12),
    p_aimantation VARCHAR(12),
    p_flottabilite VARCHAR(12),
    p_impermeabilite VARCHAR(12),
    p_precaution TEXT DEFAULT 'Pas d\'info',
    p_verification TEXT,
    p_prealable TEXT,
    p_findevie TEXT,
    p_commentaire TEXT,
    PRIMARY KEY (p_id)
)
ENGINE=INNODB;



CREATE TABLE NameMateriaux (
    n_m_id VARCHAR(32),
    n_m_date VARCHAR(32),
    n_m_nommodif VARCHAR(32),
    n_m_nom VARCHAR(32),
    n_m_famille VARCHAR(32),
    n_m_provenance VARCHAR(32),
    n_m_distance VARCHAR(32),
    n_m_fournisseur VARCHAR(32),
    n_m_traitement VARCHAR(32),
    n_m_fabrication VARCHAR(32),
    n_m_qualitedefaut VARCHAR(32),
    n_m_application VARCHAR(32),
    n_m_prix VARCHAR(32),
    n_m_composition VARCHAR(32),
    n_m_massevolumique VARCHAR(32),
    n_m_young VARCHAR(32),
    n_m_poisson VARCHAR(32),
    n_m_limiteelast VARCHAR(32),
    n_m_resistance_traction VARCHAR(32),
    n_m_resistance_compression VARCHAR(32),
    n_m_vickers VARCHAR(32),
    n_m_tenacite VARCHAR(32),
    n_m_temp_fusion VARCHAR(32),
    n_m_temp_mini VARCHAR(32),
    n_m_temp_maxi VARCHAR(32),
    n_m_chaleurspecifique VARCHAR(32),
    n_m_coefficientdilatation VARCHAR(32),
    n_m_conductivite_thermique VARCHAR(32),
    n_m_resistivite_elec VARCHAR(32),
    n_m_optique VARCHAR(32),
    n_m_durabilite_aqueux VARCHAR(32),
    n_m_durabilite_acide VARCHAR(32),
    n_m_durabilite_base VARCHAR(32),
    n_m_durabilite_huile VARCHAR(32),
    n_m_durabilite_alcool VARCHAR(32),
    n_m_durabilite_gaz VARCHAR(32),
    n_m_durabilite_construit VARCHAR(32),
    n_m_durabilite_froid VARCHAR(32),
    n_m_durabilite_temp_moyenne VARCHAR(32),
    n_m_durabilite_chaud VARCHAR(32),
    n_m_inflammabilite VARCHAR(32),
    n_m_energiegrise VARCHAR(32),
    n_m_co2_p VARCHAR(32),
    n_m_eau_p VARCHAR(32),
    n_m_recyclable VARCHAR(32),
    n_m_reutilisable VARCHAR(32),
    n_m_biodegradable VARCHAR(32),
    n_m_incinerable VARCHAR(32),
    n_m_renouvelable VARCHAR(32),
    n_m_toxicite VARCHAR(32),
    n_m_productionannuelle VARCHAR(32),
    n_m_reserves VARCHAR(32),
    n_m_commentaire VARCHAR(32)
)
ENGINE=INNODB;



CREATE TABLE NamePieces (
    n_p_id VARCHAR(32),
    n_p_date VARCHAR(32),
    n_p_nommodif VARCHAR(32),
    n_p_nom VARCHAR(32),
    n_p_materiau_principal VARCHAR(32),
    n_p_materiau_secondaire VARCHAR(32),
    n_p_forme VARCHAR(32),
    n_p_longueur VARCHAR(32),
    n_p_largeur VARCHAR(32),
    n_p_hauteur VARCHAR(32),
    n_p_quantite VARCHAR(32),
    n_p_utilisation VARCHAR(32),
    n_p_outil VARCHAR(32),
    n_p_etat VARCHAR(32),
    n_p_utilisation_init VARCHAR(32),
    n_p_thermique VARCHAR(32),
    n_p_acoustique VARCHAR(32),
    n_p_electrique VARCHAR(32),
    n_p_resistance VARCHAR(32),
    n_p_flexibilite VARCHAR(32),
    n_p_elasticite VARCHAR(32),
    n_p_optique VARCHAR(32),
    n_p_aimantation VARCHAR(32),
    n_p_flottabilite VARCHAR(32),
    n_p_impermeabilite VARCHAR(32),
    n_p_precaution VARCHAR(32),
    n_p_verification VARCHAR(32),
    n_p_prealable VARCHAR(32),
    n_p_findevie VARCHAR(32),
    n_p_commentaire VARCHAR(32)
)
ENGINE=INNODB;